INSERT INTO physical_quantities 
(name, display_unit, description, conversion_factor, conversion_exponent, m_exp, kg_exp, s_exp)
VALUES
-- DISTANCE
('distance', 'm', 'Walking, running, cycling distance', 1, 0, 1, 0, 0),
('distance', 'km', 'Longer distances (running, cycling)', 1, 3, 1, 0, 0),
('distance', 'cm', 'Body measurements, height tracking', 1, -2, 1, 0, 0),

-- WEIGHT
('weight', 'kg', 'Body weight, lifting, general mass tracking', 1, 0, 0, 1, 0),
('weight', 'g', 'Food portions, nutrition tracking', 1, -3, 0, 1, 0),
('weight', 'mg', 'Medicine, supplements', 1, -6, 0, 1, 0),

-- TIME
('time', 's', 'Stopwatch, duration tracking', 1, 0, 0, 0, 1),
('time', 'minute', 'Shorter durations, workouts, meditation', 6, 1, 0, 0, 1),
('time', 'hour', 'Sleep, workouts, daily tracking', 36, 2, 0, 0, 1),

-- VOLUME
('volume', 'm³', 'Scientific measurements, storage volume', 1, 0, 3, 0, 0),
('volume', 'L', 'Water intake, beverages', 1, -3, 3, 0, 0),
('volume', 'mL', 'Small liquid quantities', 1, -6, 3, 0, 0),

-- SPEED
('speed', 'm/s', 'Scientific / exact speed tracking', 1, 0, 1, 0, -1),
('speed', 'km/h', 'Running, cycling speed tracking', 2778, -4, 1, 0, -1);

INSERT INTO exercises (name, body_part, measurement_type, equipment) VALUES
-- Chest exercises
('Bench Press', 'chest', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Incline Bench Press', 'chest', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Decline Bench Press', 'chest', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Close-Grip Bench Press', 'chest', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Feet-Up Bench Press', 'chest', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Pin Bench Press', 'chest', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Dumbbell Bench Press', 'chest', 'weight_reps', ARRAY['dumbbell', 'bench']::exercise_equipment[]),
('Dumbbell Incline Press', 'chest', 'weight_reps', ARRAY['dumbbell', 'bench']::exercise_equipment[]),
('Dumbbell Decline Press', 'chest', 'weight_reps', ARRAY['dumbbell', 'bench']::exercise_equipment[]),
('Dumbbell Fly', 'chest', 'weight_reps', ARRAY['dumbbell', 'bench']::exercise_equipment[]),
('Dumbbell Pullover', 'chest', 'weight_reps', ARRAY['dumbbell', 'bench']::exercise_equipment[]),
('Chest Press', 'chest', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Pec Deck (Chest Fly)', 'chest', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Seated Chest Fly Machine', 'chest', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Crossover (Chest Fly)', 'chest', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Push-Up', 'chest', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Knee Push-Up', 'chest', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Diamond Push-Up', 'chest', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Wide Push-Up', 'chest', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Narrow Push-Up', 'chest', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Dip (Parallel Bar or Bench)', 'chest', 'reps', ARRAY['body_weight', 'bench']::exercise_equipment[]),
('Smith Machine Bench Press', 'chest', 'weight_reps', ARRAY['machine', 'bench']::exercise_equipment[]),
('Seated Dip Machine', 'chest', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Assisted Dip Machine', 'chest', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Suspension Trainer (TRX) Push-Up', 'chest', 'reps', ARRAY['other']::exercise_equipment[]),
('Medicine Ball Wall Ball', 'chest', 'reps', ARRAY['other']::exercise_equipment[]),
('Resistance Band Chest Press', 'chest', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Chest Fly', 'chest', 'reps', ARRAY['band']::exercise_equipment[]),

-- Shoulder exercises
('Overhead Press (Seated or Standing)', 'shoulders', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Seated Barbell Overhead Press', 'shoulders', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Behind the Neck Press', 'shoulders', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Snatch Grip Behind the Neck Press', 'shoulders', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Dumbbell Shoulder Press', 'shoulders', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Lateral Raise', 'shoulders', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Front Raise', 'shoulders', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Rear Delt Fly', 'shoulders', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Arnold Press', 'shoulders', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Upright Row', 'shoulders', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Barbell Front Raise', 'shoulders', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Barbell Upright Row', 'shoulders', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Barbell Rear Delt Row', 'shoulders', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Shoulder Press Machine', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Seated Overhead Press Machine', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Seated Lateral Raise Machine', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Seated Rear Delt Fly Machine', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Smith Machine Shoulder Press', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Lateral Raise', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Front Raise', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Rear Delt Fly', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Upright Row', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Face Pull', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Rope Face Pull', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Single-Arm Lateral Raise', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Single-Arm Front Raise', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Single-Arm Rear Delt Fly', 'shoulders', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Pike Push-Up', 'shoulders', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Handstand Push-Up', 'shoulders', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Upright Row', 'shoulders', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Barbell Shrug', 'shoulders', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Trap Bar Shrug', 'shoulders', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Dumbbell Shrug', 'shoulders', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Resistance Band Lateral Raise', 'shoulders', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Front Raise', 'shoulders', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Overhead Press', 'shoulders', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Face Pull', 'shoulders', 'reps', ARRAY['band']::exercise_equipment[]),
('Kettlebell Bottoms-Up Press', 'shoulders', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Halo', 'shoulders', 'reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Windmill', 'shoulders', 'reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Sots Press', 'shoulders', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),

-- Core exercises
('Plank', 'core', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Side Plank', 'core', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Crunch', 'core', 'weight_reps', ARRAY['body_weight']::exercise_equipment[]),
('Leg Raise (Hanging or Lying)', 'core', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Russian Twist', 'core', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Cable Crunch (Abdominal)', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Woodchop (Oblique)', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Pallof Press', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Rope Crunch', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Rope Woodchop', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Single-Arm Pallof Press', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Abdominal Crunch Machine', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Rotary Torso Machine', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Back Extension (Superman)', 'core', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Back Extension Machine', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Seated Back Extension Machine', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Bird Dog', 'core', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Superman Hold', 'core', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Hollow Body Hold', 'core', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Wall Sit', 'core', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Superman Pull', 'core', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Superman Fly', 'core', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Bicycle Crunches', 'core', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Reverse Crunches', 'core', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Medicine Ball Russian Twist', 'core', 'weight_reps', ARRAY['other']::exercise_equipment[]),
('Kettlebell Russian Twist', 'core', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Resistance Band Pallof Press', 'core', 'weight_reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Woodchop', 'core', 'weight_reps', ARRAY['band']::exercise_equipment[]),
('Dumbbell Side Bend', 'core', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Woodchop', 'core', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Cable Ab Crunch Machine', 'core', 'weight_reps', ARRAY['machine']::exercise_equipment[]),

-- Arms exercises
('Barbell Curl', 'arms', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Barbell Preacher Curl', 'arms', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Barbell Standing Triceps Extension', 'arms', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Barbell Incline Triceps Extension', 'arms', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Barbell Lying Triceps Extension', 'arms', 'weight_reps', ARRAY['barbell', 'bench']::exercise_equipment[]),
('Barbell Wrist Curl', 'arms', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Dumbbell Curl (Bicep)', 'arms', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Hammer Curl', 'arms', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Tricep Extension', 'arms', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Wrist Curl', 'arms', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Kickback (Tricep)', 'arms', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Concentration Curl', 'arms', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Skull Crusher', 'arms', 'weight_reps', ARRAY['dumbbell', 'bench']::exercise_equipment[]),
('Dumbbell Zottman Curl', 'arms', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Preacher Curl', 'arms', 'weight_reps', ARRAY['dumbbell', 'bench']::exercise_equipment[]),
('Dumbbell Wrist Extension', 'arms', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Wrist Flexion', 'arms', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Cable Tricep Pushdown', 'arms', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Bicep Curl', 'arms', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Overhead Tricep Extension', 'arms', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Rope Hammer Curl', 'arms', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Rope Tricep Pushdown', 'arms', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Single-Arm Tricep Pushdown', 'arms', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Single-Arm Hammer Curl', 'arms', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Tricep Extension Machine', 'arms', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Bicep Curl Machine', 'arms', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Resistance Band Bicep Curl', 'arms', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Tricep Extension', 'arms', 'reps', ARRAY['band']::exercise_equipment[]),

-- Back exercises
('Barbell Row (Bent-Over)', 'back', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Pendlay Row', 'back', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Dumbbell Row (One-Arm or Bent-Over)', 'back', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Renegade Row', 'back', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Lat Pulldown', 'back', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Seated Row', 'back', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Assisted Pull-Up Machine', 'back', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Pulldown (Lat)', 'back', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Row (Seated)', 'back', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Straight-Arm Pulldown', 'back', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Single-Arm Row', 'back', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Single-Arm Straight-Arm Pulldown', 'back', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Pull-Up', 'back', 'reps', ARRAY['body_weight', 'pull_up_bar']::exercise_equipment[]),
('Chin-Up', 'back', 'reps', ARRAY['body_weight', 'pull_up_bar']::exercise_equipment[]),
('Inverted Row', 'back', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Superman', 'back', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Resistance Band Pull-Apart', 'back', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Row', 'back', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Seated Row', 'back', 'reps', ARRAY['band']::exercise_equipment[]),
('Kettlebell Row', 'back', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Suspension Trainer (TRX) Row', 'back', 'reps', ARRAY['other']::exercise_equipment[]),

-- Legs exercises
('Front Squat', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Back Squat', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Pause Squat', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Pin Squat', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Sumo Squat', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Zercher Squat', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Zombie Squat', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Barbell Lunge', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Barbell Walking Lunge', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Reverse Barbell Lunge', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Barbell Hack Squat', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Safety Bar Squat', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Barbell Calf Raise', 'legs', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Dumbbell Lunge', 'legs', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Squat', 'legs', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Goblet Squat', 'legs', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Stiff-Leg Deadlift', 'legs', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Calf Raise', 'legs', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Step-Up', 'legs', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Bulgarian Split Squat', 'legs', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Romanian Deadlift', 'legs', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Leg Press', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Leg Extension', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Leg Curl (Seated or Lying)', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Hack Squat Machine', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Smith Machine Squat', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Calf Raise Machine (Seated or Standing)', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Seated Calf Raise', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Standing Calf Raise', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Leg Adduction Machine', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Leg Abduction Machine', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Inner/Outer Thigh Machine (Adductor/Abductor)', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Glute Kickback Machine', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Seated Leg Press', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Leg Curl', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Kickback (Glute)', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Hip Abduction/Adduction', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Cable Single-Arm Hip Abduction/Adduction', 'legs', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Squat (Air Squat)', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Lunge', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Pistol Squat (Single-Leg)', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Calf Raise (Bodyweight)', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Glute Bridge', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Donkey Kicks', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Fire Hydrants', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Frog Jump', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Squat Jump', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Lunge Jump', 'legs', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Kettlebell Goblet Squat', 'legs', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Deadlift', 'legs', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Pistol Squat', 'legs', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Lunge', 'legs', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Resistance Band Squat', 'legs', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Leg Press', 'legs', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Glute Kickback', 'legs', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Lateral Lunge', 'legs', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Hamstring Curl', 'legs', 'reps', ARRAY['band']::exercise_equipment[]),
('Resistance Band Calf Raise', 'legs', 'reps', ARRAY['band']::exercise_equipment[]),
('Sandbag Squat', 'legs', 'weight_reps', ARRAY['other']::exercise_equipment[]),
('Sandbag Lunge', 'legs', 'weight_reps', ARRAY['other']::exercise_equipment[]),

-- Olympic exercises
('Snatch', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Clean', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Clean and Jerk', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Hang Clean', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Hang Power Clean', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Hang Power Snatch', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Hang Snatch', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Power Clean', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Power Snatch', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Block Clean', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Block Snatch', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Kettlebell Clean and Press', 'olympic', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Snatch', 'olympic', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell High Pull', 'olympic', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Power Clean (variation)', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Front Squat (as accessory)', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Squat Clean', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Push Jerk', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Power Snatch (variation)', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Squat Snatch', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Clean Pull', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Snatch Pull', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('High Pull', 'olympic', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),

-- Full Body exercises
('Deadlift (Conventional)', 'full_body', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Sumo Deadlift', 'full_body', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Stiff-Legged Deadlift', 'full_body', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Romanian Deadlift', 'full_body', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Deficit Deadlift', 'full_body', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Pause Deadlift', 'full_body', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Trap Bar Deadlift', 'full_body', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Good Morning', 'full_body', 'weight_reps', ARRAY['barbell']::exercise_equipment[]),
('Jefferson Curl', 'full_body', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Deadlift', 'full_body', 'weight_reps', ARRAY['dumbbell']::exercise_equipment[]),
('Dumbbell Farmer''s Walk', 'full_body', 'distance_time', ARRAY['dumbbell']::exercise_equipment[]),
('Seated Row (partial back, but compound)', 'full_body', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Burpee', 'full_body', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Mountain Climber', 'full_body', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Handstand Hold', 'full_body', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Bear Crawl', 'full_body', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Crab Walk', 'full_body', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Tuck Jump', 'full_body', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Kettlebell Swing', 'full_body', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Turkish Get-Up', 'full_body', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Thruster', 'full_body', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Farmer''s Carry', 'full_body', 'distance_time', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Slingshot', 'full_body', 'weight_reps', ARRAY['kettlebell']::exercise_equipment[]),
('Kettlebell Figure Eight', 'full_body', 'reps', ARRAY['kettlebell']::exercise_equipment[]),
('Medicine Ball Slam', 'full_body', 'reps', ARRAY['other']::exercise_equipment[]),
('Battle Rope Waves', 'full_body', 'time', ARRAY['other']::exercise_equipment[]),
('Sled Push/Pull', 'full_body', 'distance_time', ARRAY['other']::exercise_equipment[]),
('Farmer''s Walk (with weights)', 'full_body', 'distance_time', ARRAY['other']::exercise_equipment[]),
('Tire Flip', 'full_body', 'reps', ARRAY['other']::exercise_equipment[]),
('Sandbag Carry', 'full_body', 'distance_time', ARRAY['other']::exercise_equipment[]),
('Sandbag Clean', 'full_body', 'weight_reps', ARRAY['other']::exercise_equipment[]),
('Sandbag Shoulder Press', 'full_body', 'weight_reps', ARRAY['other']::exercise_equipment[]),

-- Cardio exercises
('Treadmill Running/Walking', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Stationary Cycling', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Elliptical Trainer', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Rowing Machine', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Stair Climber/Stepper', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Jump Rope', 'cardio', 'time', ARRAY['other']::exercise_equipment[]),
('Battle Ropes', 'cardio', 'time', ARRAY['other']::exercise_equipment[]),
('Swimming (if gym has pool)', 'cardio', 'distance_time', ARRAY['body_weight']::exercise_equipment[]),
('Indoor Cycling (Spin Bike)', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Assault Bike/Air Bike', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Ski Erg', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('High-Intensity Interval Training (HIIT) Circuits (e.g., sprints)', 'cardio', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Step Aerobics', 'cardio', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Boxing/Kickboxing (Heavy Bag)', 'cardio', 'time', ARRAY['other']::exercise_equipment[]),
('Recumbent Bike', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Arc Trainer', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Jacob''s Ladder', 'cardio', 'time', ARRAY['machine']::exercise_equipment[]),
('VersaClimber', 'cardio', 'time', ARRAY['machine']::exercise_equipment[]),
('Fan Bike Intervals', 'cardio', 'time', ARRAY['machine']::exercise_equipment[]),
('Incline Walking (Treadmill)', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Bicycling', 'cardio', 'distance_time', ARRAY['other']::exercise_equipment[]),
('Cycle Ergometer', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Recumbent Cycle', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Elliptical Cross Trainer', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Climber', 'cardio', 'time', ARRAY['machine']::exercise_equipment[]),
('Ladder Mill', 'cardio', 'time', ARRAY['machine']::exercise_equipment[]),
('Stair Mill', 'cardio', 'time', ARRAY['machine']::exercise_equipment[]),
('Jumping Jacks', 'cardio', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Burpees', 'cardio', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('High Knees', 'cardio', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Mountain Climbers', 'cardio', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Jumping Rope', 'cardio', 'time', ARRAY['other']::exercise_equipment[]),
('Shadow Boxing', 'cardio', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Dance Cardio', 'cardio', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Zumba (if class available)', 'cardio', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Treadmill Sprints', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Rowing Intervals', 'cardio', 'distance_time', ARRAY['machine']::exercise_equipment[]),
('Stair Sprints', 'cardio', 'time', ARRAY['body_weight']::exercise_equipment[]),

-- Other exercises
('Cable Rope Pull (misc variations)', 'other', 'weight_reps', ARRAY['machine']::exercise_equipment[]),
('Wall Angels', 'other', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Arm Circles', 'other', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Leg Circles', 'other', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('L-Sit Hold', 'other', 'time', ARRAY['body_weight']::exercise_equipment[]),
('V-Sit Hold', 'other', 'time', ARRAY['body_weight']::exercise_equipment[]),
('Flutter Kicks', 'other', 'reps', ARRAY['body_weight']::exercise_equipment[]),
('Scissor Kicks', 'other', 'reps', ARRAY['body_weight']::exercise_equipment[]);